apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: devdemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devdemo 
    spec:
      containers:
        - name: devdemo 
          image: tugboat.azurecr.io/devdemo 
          ports:
          - containerPort: 8080